#ifndef PACKETS_H
#define PACKETS_H


enum S2C_PROTOCOL{
	S2C_SIEGEGUNSET,
	S2C_SIEGEGUNCONTROL,
	S2C_REQGUID,
	S2C_REQCRC,
	S2C_ITEMINFO,
	S2C_PUTONITEM,
	S2C_PUTOFFITEM,
	S2C_INSERTITEM,
	S2C_TRASHITEM,
	S2C_UPDATEITEMNUM,
	S2C_SKILLADDVALUE,		// 10
	S2C_SKILLREDISTRIBUTE,
	S2C_PKBULLETININFO,
	S2C_GETSTALLINFO,
	S2C_MORA,
	S2C_NOTICE,
	S2C_SKILLINFO,
	S2C_PLAYERINFO,
	S2C_FRD,
	S2C_MAIL,
	S2C_LUCKYBLOW,			// 20
	S2C_MSTATEEX,
	S2C_MAPSTATE,
	S2C_CHANGEFACE,
	S2C_PLAYER_ANIMATION,
	S2C_DELPLAYERINFO,
	S2C_RESTOREPLAYER,
	S2C_ANS_LOAD,
	S2C_ANS_START,
	S2C_ANS_RESTART,
	S2C_ALIVE,				// 30
	S2C_GETMYTELPT,
	S2C_SETMYTELPT,
	S2C_MOVEBEFORE,
	S2C_MOVEPLAYER_ON,
	S2C_MOVEPLAYER_END,
	S2C_MOVEMONSTER_ON,
	S2C_MOVEMONSTER_END,
	S2C_MOVENPC_ON,
	S2C_MOVENPC_END,
	S2C_MOVEHORSE_ON_____RESERVED,	// 40
	S2C_MOVEHORSE_END_____RESERVED,
	S2C_CODE,
	S2C_ANS_LOGIN,
	S2C_ANS_NEWPLAYER,
	S2C_CLOSE,
	S2C_GSTATE,
	S2C_PET,
	S2C_TOOJUN,
	S2C_KAL21,
	S2C_CREATEPLAYER,		// 50
	S2C_CREATEMONSTER,
	S2C_CREATENPC,
	S2C_CREATEHORSE_____RESERVED,
	S2C_CREATEITEM,
	S2C_REMOVEPLAYER,
	S2C_REMOVEMONSTER,
	S2C_REMOVENPC,
	S2C_REMOVEHORSE_____RESERVED,
	S2C_REMOVEITEM,
	S2C_CHATTING,			// 60
	S2C_ACTION,
	S2C_ATTACK,
	S2C_SKILL,
	S2C_INFODIE,
	S2C_DEFENSE,
	S2C_PROPERTY,
	S2C_MESSAGE,
	S2C_MESSAGEV,
	S2C_UPDATEPROPERTY,
	S2C_TELEPORT,			// 70
	S2C_MSTATE,
	S2C_UPDATEMPROPERTY,
	S2C_EFFECT,
	S2C_SENDHTML,
	S2C_ASKTRADE,
	S2C_ITEMLIST,
	S2C_OPENTRADE,
	S2C_CLOSETRADE,
	S2C_SHOWOFFITEM,
	S2C_ANS_TRADEITEM,		// 80
	S2C_SKILLUP,
	S2C_ASKPARTY,
	S2C_PARTYMEMPOS,
	S2C_PARTYINFO,
	S2C_UPDATEPARTY,
	S2C_SAVEQUEST,
	S2C_QUESTINFO,
	S2C_STORAGEINFO,
	S2C_INSERT_SITEM,
	S2C_UPDATE_SITEMNUM,	// 90
	S2C_UPDATEITEMEND,
	S2C_UPDATEITEMINFO,
	S2C_ANS_GAMEEXIT,
	S2C_GUILD,
	S2C_MESSAGEPK,
	S2C_ASKPVP,
	S2C_ANS_COPYPLAYER,
	S2C_BILLINGINFO,
	S2C_BILLINGALERT,
	S2C_MLM,				// 100
	S2C_MOVEDASHPLAYER_ON,
	S2C_MOVEDASHPLAYER_END,
	S2C_SHORTCUT,
	S2C_EFFECTMIX,
	S2C_MIX,
	S2C_BATTLEFIELD,
	S2C_HACKSHEILDCRC,
	S2C_TOWERCRASH,
	S2C_NOTICE_2,
	S2C_EVENT_SNOWFALL_COUNT,	// 110
	S2C_ISLAND_SNOW,
	S2C_ANS_BUYITEM_HONOR,
	S2C_ANS_BUYITEM_HONOR_FAILED,
	S2C_ANS_HONOR_INFO,
	S2C_EVENT_SLEEPINGACCOUNT, 
	S2C_EVENT_NEWACCOUNT,  
	S2C_LEARNSKILL_HONOR_FAILED,
	S2C_ENCHANT_FAILED,
	S2C_ANS_SKILLUP_OVERRUN,
	S2C_BATTLEFIELD_3_2,	// 120
	S2C_BATTLEFIELD_3_3,
	S2C_LORDPROTECT,
	S2C_ANS_SHOWDOWN,
	S2C_NEWYEARTHROW,
	S2C_REQ_SHOWDOWN,

	S2C_EFFECT_EX,
	S2C_SENDSEED,
	S2C_OVERLAPSKILL,
	S2C_ANS_DUNGEON,
	S2C_EVENT_FISHING,
	S2C_RESULT_CODE,
	S2C_DATELIMITTIME,
	S2C_CREATESTRUCTURE,
	S2C_REMOVESTRUCTURE,
	S2C_STRUCTURE,
	S2C_ARMY,

	S2C_DOGGEBI_LORD_EVENT,
	S2C_HAPPY_HOUR,
	S2C_ISLAND_OF_BATTLEFIELD,		// 3-4
	S2C_ARMYCHATTING,
	S2C_ARMY_MEMBER_POS,
	S2C_ARMY_MEMBER_INFO,
	S2C_SECOND_LOGIN,
	S2C_PLAYER_SUMMON,
	S2C_GSTATE_EX,
	S2C_OWN_TELEPORT,
	S2C_QUICK_RUNNING,
	S2C_MSTATE_EX,
	S2C_RETURN_USER,
	S2C_RETURN_EVENT,

	S2C_GIVEUP_QUEST,

	S2C_ASK_PLATOON,
	S2C_ASK_PARTY_IN_PLATOON,
	S2C_PLATOON_INFO,
	S2C_UPGRADE_PARTY_BY_PLATOON,

	S2C_ASK_COMPANY,
	S2C_ASK_PARTY_IN_COMPANY,
	S2C_ASK_PLATOON_IN_COMPANY,
	S2C_COMPANY_INFO,
	S2C_PLATOON_HEAD_LIST,

	S2C_SERVER_MOVE_REGIST,
	S2C_WHANIN_USER_MOVE,

	S2C_RESTORE_EXP,
	S2C_MESSAGE_EX,
	S2C_MESSAGEV_EX,

	S2C_TOWER_OF_PRIEST,

	S2C_TOWER_OF_PRIEST_OP_EVENT_BEGIN,
	S2C_TOWER_OF_PRIEST_OP_EVENT_END,

	S2C_TOWER_OF_PRIEST_EN_EVENT_BEGIN,
	S2C_TOWER_OF_PRIEST_EN_EVENT_END,

	S2C_ILRYER_EVENT,
	S2C_MOVEDASH_ON,
	S2C_MOVEDASH_END,
	S2C_DASHSKILL,
	S2C_ATTACK_STOP,


	S2C_TAIWAN_BOKJOOMONEY,
	S2C_HELL_ISLAND,
	S2C_SKY_BENEFIT,
	S2C_ITEM_COOLTIME,

	S2C_REQUEST_SHOWTAEHOOEVENT,
	S2C_REJECT_GOTOTAEHOOEVENT,
	S2C_FINISH_TAEHOOEVENT,

	S2C_DAMAGE_REFLECT,

	S2C_UPDATE_HUNTEDMONSTERCOUNT,
	S2C_FAILED_QUESTBYTIME,

	S2C_UPDATE_HUNTMONSTERSTATE,

	S2C_ITEMCHARGEEVENT_NPC,
	S2C_ITEMCHARGEEVENT_PLAYERLIST,
	S2C_ITEMCHARGEEVENT_ERROR,

	S2C_PSTATE,
	S2C_CREATE_PET,	

	S2C_AUCTION_REPORT_REQUESTEDPROCESS,
	S2C_AUCTION_UPDATE_REQUESTEDITEMLIST,

	S2C_NOTICE_3,
	S2C_NOTICE_LUNA_EVENT_2010,

	S2C_WC_PROTOCOL,
	S2C_WC_MESSAGE,

	S2C_IF_PROTOCOL,
	S2C_IF_MESSAGE,

	S2C_PVPSKILL_NODAMAGE,
	S2C_RIDING,
	S2C_CREATERIDING,
	S2C_DELETERIDING,

	S2C_GC_PROTOCOL,
	S2C_GC_MESSAGE,

	S2C_END,
};

enum C2S_PROTOCOL
{
	C2S_RESTOREPLAYER,
	C2S_ACKGUID,
	C2S_LOGIN,
	C2S_ACKCRC,
	C2S_NEWPLAYER,
	C2S_ALIVE,
	C2S_COPYPLAYER,
	C2S_DELPLAYER,
	C2S_CONNECT,
	C2S_ANS_CODE,
	C2S_LOADPLAYER,	// 10

	C2S_START,		// 11

	C2S_ATTACK,
	C2S_SKILL,
	C2S_CHATTING,
	C2S_TELEPORT,
	C2S_RESTART,
	C2S_MOVE_ON,
	C2S_MOVE_END,
	C2S_ASKNPC,
	C2S_ITEMLIST,	// 20
	C2S_BUYITEM,
	C2S_SELLITEM,
	C2S_DROPITEM,
	C2S_GAMEEXIT,
	C2S_SHOWOFFITEM,
	C2S_ACTION,
	C2S_UPDATEPROPERTY,
	C2S_REST,
	C2S_PICKUPITEM,
	C2S_USEITEM,	// 30
	C2S_ASKTRADE,
	C2S_ANS_ASKTRADE,
	C2S_CANCELTRADE,
	C2S_REVIVAL,
	C2S_SIEGEGUN,
	C2S_SIEGEGUNSET,
	C2S_SIEGEGUNCONTROL, 
	C2S_LEARNSKILL,
	C2S_SKILLUP,
	C2S_PRESKILL,//40
	C2S_ASKPARTY,
	C2S_ANS_ASKPARTY,
	C2S_GUILD,
	C2S_LEAVEPARTY,
	C2S_EXILEPARTY,
	C2S_PUTINSTORAGE,
	C2S_PUTOUTSTORAGE,
	C2S_QUEST,
	C2S_STORAGEINFO,
	C2S_PET,	// 50
	C2S_SAVEREVIVALPT,
	C2S_ENCHANTITEM,
	C2S_SETSTALLINFO,
	C2S_MOD2NDJOB,			
	C2S_UPPER_CHANCE_STONE,
	C2S_PLAYER_ANIMATION,
	C2S_TRADEITEM,
	C2S_TRASHITEM,
	C2S_FRD,
	C2S_PUTONITEM,	// 60
	C2S_PUTOFFITEM,
	C2S_SWITCHSTALL,
	C2S_QUESTJOB_END,
	C2S_GETSTALLINFO,	
	C2S_BUYITEMATSTALL,
	C2S_COOKING,
	C2S_ANS_REVIVALSKILL,
	C2S_SKILLREDISTRIBUTE,
	C2S_DANJI,
	C2S_INITSTAT,	// 70
	C2S_PKBULLETININFO,
	C2S_ASKPVP,	
	C2S_ANS_ASKPVP,
	C2S_TRANSFORM,			
	C2S_BLESS,
	C2S_TRANSFORMSKILL,
	C2S_MLM,
	C2S_PKSTATUS,
	C2S_SHORTCUT,
	C2S_SETMYTELPT,	
	C2S_UPGRADEITEM,// 80
	C2S_MAIL,
	C2S_CANCELITEMMONSTER,
	C2S_GETITEMMONSTER,
	C2S_CHANGEGUILDNAME,
	C2S_CHANGEPLAYERNAME,
	C2S_NPC,
	C2S_MIXING,
	C2S_MIXSETDEFENSE,
	C2S_BATTLEFIELD,
	C2S_HSCLIENTERRCODE,	// 90
	C2S_TOWERCRASH,
	C2S_EVENT_SNOWFALL,
	C2S_REQ_HONOR_INFO,
	C2S_EVENT_SNOWFALL_COUNT,
	C2S_REQ_BUYITEM_HONOR,
	C2S_LEARNSKILL_HONOR,
	C2S_REQ_SKILLUP_OVERRUN,
	C2S_REQ_SHOWDOWN,
	C2S_LORDPROTECT,
	C2S_UPDATE_HONOR_SHOW_OPTION, 	// 100
	C2S_ANS_SHOWDOWN,
	C2S_ITEM_BOMB,	
	C2S_ITEM_TELEPORT,
	C2S_ITEM_INVINCIBILITY,	

	C2S_REQUESTSEED,
	C2S_ANS_DUNGEON,
	C2S_REQ_DUNGEON,
	C2S_LOCKITEM,
	C2S_UNLOCKITEM_LEVEL1,
	C2S_UNLOCKITEM_LEVEL2,	// 110

	C2S_TASK_COMPLETED,     
	C2S_BATTLEFIELD_3_3, 
	C2S_STRUCTURE,
	C2S_ARMY,

	C2S_ISLAND_OF_BATTLEFIELD,
	C2S_SECOND_LOGIN,

	C2S_PLAYER_SUMMON,
	C2S_OWN_TELEPORT,

	C2S_GIVEUP_QUEST,

	C2S_ASK_PLATOON,	// 120
	C2S_ASK_PARTY_IN_PLATOON,
	C2S_ANS_ASK_PLATOON,
	C2S_ANS_ASK_PARTY_IN_PLATOON,
	C2S_LEAVE_PLATOON,
	C2S_EXILE_PLATOON,
	C2S_UPGRADE_PARTY_BY_PLATOON,
	C2S_LEAVE_ALL_PLATOON,

	C2S_ASK_COMPANY,	
	C2S_ASK_PLATOON_IN_COMPANY,
	C2S_ANS_ASK_COMPANY,		// 130
	C2S_ANS_ASK_PLATOON_IN_COMPANY,
	C2S_ASK_PARTY_IN_COMPANY,
	C2S_ANS_ASK_PARTY_IN_COMPNAY,
	C2S_LEAVE_COMPANY,
	C2S_EXILE_COMPANY,
	C2S_ELEMENT_CHANGE,
	C2S_UPGRADE_PLATOON_BY_COMPANY,
	C2S_LEAVE_ALL_COMPANY,	

	C2S_ASK_PLATOON_HEAD_LIST,
	C2S_RESTORE_EXP,	// 140

	C2S_MONSTER_SPAWN,
	C2S_HELL_ISLAND,

	C2S_SELLITEM_HONOR,
	C2S_SKY_BENEFIT,
	C2S_USETHROWITEM, 

	C2S_REQUEST_GOBACKTAEHOOEVENT,

	C2S_AUCTION_REQUEST_REGISTERITEM,
	C2S_AUCTION_REQUEST_TENDERITEM,
	C2S_AUCTION_REQUEST_BUYDIRECTLY,
	C2S_AUCTION_REQUEST_UPDATEITEMLIST,	// 150

	C2S_CHANGE_APPEARANCE,

	C2S_WC_LOGIN,
	C2S_WC_SECOND_LOGIN,
	C2S_WC_PROTOCOL,

	C2S_ENCHANTITEM_CHEONJU,



	C2S_IF_PROTOCOL,

	C2S_RESTOREITEM,
	C2S_RESTOREITEM_ASK,

	C2S_RIDING,

	C2S_SKYSKILLREDISTRIBUTE,				// 160

	C2S_GC_PROTOCOL,

	C2S_END,
};


#endif // PACKETS_H